import type {
  InpatientUnitDto,
  InpatientWardDto,
  InpatientBedDto,
  InpatientAdmissionRequestDto,
  InpatientAdmissionDto,
  InpatientTransferDto,
  InpatientNursingAssessmentDto,
  InpatientVitalObservationDto,
  InpatientDoctorRoundDto,
  InpatientDischargePlanDto,
  InpatientDischargeSummaryDto,
  InpatientBedTurnaroundDto,
  InpatientBedBlockDto,
  InpatientAuditTraceDto,
  InpatientOverviewMetricsDto,
  InpatientAnalyticsDto
} from '@docsearch/api-contracts';

const T_ID = '11111111-1111-4111-8111-111111111111';
const P_ID = '22222222-2222-4222-8222-222222222222';
const O_ID = '33333333-3333-4333-8333-333333333333';
const B_ID = '44444444-4444-4444-8444-444444444444';

export const mockInpatientUnits: InpatientUnitDto[] = [
  {
    id: 'unit-001',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    unitCode: 'UNIT-CCU',
    unitName: 'Critical Care Division',
    unitType: 'CRITICAL_CARE',
    specialty: 'Intensive Care Medicine',
    building: 'Main Hospital Tower',
    floor: 'Floor 3',
    totalCapacity: 20,
    isActive: true,
    createdAt: '2026-08-01T08:00:00.000Z',
    updatedAt: '2026-08-01T08:00:00.000Z'
  },
  {
    id: 'unit-002',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    unitCode: 'UNIT-MEDSURG',
    unitName: 'Medical & Surgical Care Division',
    unitType: 'GENERAL_MEDICINE',
    specialty: 'Internal Medicine & General Surgery',
    building: 'Wing B Pavilion',
    floor: 'Floor 4',
    totalCapacity: 50,
    isActive: true,
    createdAt: '2026-08-01T08:00:00.000Z',
    updatedAt: '2026-08-01T08:00:00.000Z'
  },
  {
    id: 'unit-003',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    unitCode: 'UNIT-MATERNAL',
    unitName: 'Maternal & Child Health Division',
    unitType: 'MATERNAL_CHILD',
    specialty: 'Obstetrics & Gynecology',
    building: 'Women and Children Center',
    floor: 'Floor 2',
    totalCapacity: 30,
    isActive: true,
    createdAt: '2026-08-01T08:00:00.000Z',
    updatedAt: '2026-08-01T08:00:00.000Z'
  }
];

export const mockInpatientWards: InpatientWardDto[] = [
  {
    id: 'ward-001',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    unitId: 'unit-001',
    wardCode: 'WARD-ICU-A',
    wardName: 'Intensive Care Unit (ICU Alpha)',
    wardType: 'ICU',
    careLevel: 'LEVEL_3_ICU',
    genderPolicy: 'ALL',
    building: 'Main Hospital Tower',
    floor: 'Floor 3',
    wing: 'North Wing',
    nursingStationName: 'Station ICU-1',
    isolationCapable: true,
    ventilatorCapable: true,
    totalBeds: 12,
    activeBeds: 12,
    occupiedBeds: 9,
    blockedBeds: 1,
    cleaningBeds: 1,
    isActive: true,
    createdAt: '2026-08-01T08:00:00.000Z',
    updatedAt: '2026-08-01T08:00:00.000Z'
  },
  {
    id: 'ward-002',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    unitId: 'unit-002',
    wardCode: 'WARD-GEN-MED',
    wardName: 'General Medical Ward (4 East)',
    wardType: 'GENERAL',
    careLevel: 'TERTIARY_CARE',
    genderPolicy: 'ALL',
    building: 'Wing B Pavilion',
    floor: 'Floor 4',
    wing: 'East Wing',
    nursingStationName: 'Station 4-East',
    isolationCapable: false,
    ventilatorCapable: false,
    totalBeds: 24,
    activeBeds: 24,
    occupiedBeds: 18,
    blockedBeds: 2,
    cleaningBeds: 1,
    isActive: true,
    createdAt: '2026-08-01T08:00:00.000Z',
    updatedAt: '2026-08-01T08:00:00.000Z'
  },
  {
    id: 'ward-003',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    unitId: 'unit-002',
    wardCode: 'WARD-PRIV-DLX',
    wardName: 'Deluxe Private Pavilion (5 West)',
    wardType: 'DELUXE',
    careLevel: 'TERTIARY_CARE',
    genderPolicy: 'ALL',
    building: 'Wing B Pavilion',
    floor: 'Floor 5',
    wing: 'West Wing',
    nursingStationName: 'Station 5-West Concierge',
    isolationCapable: true,
    ventilatorCapable: true,
    totalBeds: 10,
    activeBeds: 10,
    occupiedBeds: 6,
    blockedBeds: 0,
    cleaningBeds: 1,
    isActive: true,
    createdAt: '2026-08-01T08:00:00.000Z',
    updatedAt: '2026-08-01T08:00:00.000Z'
  }
];

export const mockInpatientBeds: InpatientBedDto[] = [
  {
    id: 'bed-001',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    wardId: 'ward-001',
    wardName: 'Intensive Care Unit (ICU Alpha)',
    bedCode: 'ICU-BED-01',
    bedNumber: '01',
    bedType: 'ICU_CRITICAL',
    bedClass: 'ICU',
    status: 'OCCUPIED',
    genderEligibility: 'ALL',
    hasOxygenPort: true,
    hasSuctionPort: true,
    hasVentilator: true,
    hasCardiacMonitor: true,
    dailyChargeRate: 850.00,
    currentPatientId: 'pat-001',
    currentPatientName: 'Eleanor Vance',
    currentPatientMrn: 'MRN-2026-0081',
    currentAdmissionId: 'adm-001',
    isActive: true,
    createdAt: '2026-08-01T08:00:00.000Z',
    updatedAt: '2026-08-29T10:00:00.000Z'
  },
  {
    id: 'bed-002',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    wardId: 'ward-001',
    wardName: 'Intensive Care Unit (ICU Alpha)',
    bedCode: 'ICU-BED-02',
    bedNumber: '02',
    bedType: 'ICU_CRITICAL',
    bedClass: 'ICU',
    status: 'AVAILABLE',
    genderEligibility: 'ALL',
    hasOxygenPort: true,
    hasSuctionPort: true,
    hasVentilator: true,
    hasCardiacMonitor: true,
    dailyChargeRate: 850.00,
    isActive: true,
    createdAt: '2026-08-01T08:00:00.000Z',
    updatedAt: '2026-08-29T10:00:00.000Z'
  },
  {
    id: 'bed-003',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    wardId: 'ward-002',
    wardName: 'General Medical Ward (4 East)',
    bedCode: 'GM-401-A',
    bedNumber: '401-A',
    bedType: 'STANDARD_ELECTRIC',
    bedClass: 'GENERAL',
    status: 'OCCUPIED',
    genderEligibility: 'ALL',
    hasOxygenPort: true,
    hasSuctionPort: true,
    hasVentilator: false,
    hasCardiacMonitor: true,
    dailyChargeRate: 180.00,
    currentPatientId: 'pat-002',
    currentPatientName: 'Marcus Thorne',
    currentPatientMrn: 'MRN-2026-0142',
    currentAdmissionId: 'adm-002',
    isActive: true,
    createdAt: '2026-08-01T08:00:00.000Z',
    updatedAt: '2026-08-29T10:00:00.000Z'
  },
  {
    id: 'bed-004',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    wardId: 'ward-002',
    wardName: 'General Medical Ward (4 East)',
    bedCode: 'GM-401-B',
    bedNumber: '401-B',
    bedType: 'STANDARD_ELECTRIC',
    bedClass: 'GENERAL',
    status: 'CLEANING',
    genderEligibility: 'ALL',
    hasOxygenPort: true,
    hasSuctionPort: true,
    hasVentilator: false,
    hasCardiacMonitor: false,
    dailyChargeRate: 180.00,
    isActive: true,
    createdAt: '2026-08-01T08:00:00.000Z',
    updatedAt: '2026-08-29T10:00:00.000Z'
  },
  {
    id: 'bed-005',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    wardId: 'ward-003',
    wardName: 'Deluxe Private Pavilion (5 West)',
    bedCode: 'DLX-501',
    bedNumber: '501',
    bedType: 'STANDARD_ELECTRIC',
    bedClass: 'DELUXE',
    status: 'AVAILABLE',
    genderEligibility: 'ALL',
    hasOxygenPort: true,
    hasSuctionPort: true,
    hasVentilator: true,
    hasCardiacMonitor: true,
    dailyChargeRate: 450.00,
    isActive: true,
    createdAt: '2026-08-01T08:00:00.000Z',
    updatedAt: '2026-08-29T10:00:00.000Z'
  },
  {
    id: 'bed-006',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    wardId: 'ward-003',
    wardName: 'Deluxe Private Pavilion (5 West)',
    bedCode: 'DLX-502',
    bedNumber: '502',
    bedType: 'STANDARD_ELECTRIC',
    bedClass: 'DELUXE',
    status: 'BLOCKED',
    genderEligibility: 'ALL',
    hasOxygenPort: true,
    hasSuctionPort: true,
    hasVentilator: false,
    hasCardiacMonitor: false,
    dailyChargeRate: 450.00,
    notes: 'Air filtration & medical gas annual calibration',
    isActive: true,
    createdAt: '2026-08-01T08:00:00.000Z',
    updatedAt: '2026-08-29T10:00:00.000Z'
  }
];

export const mockInpatientAdmissionRequests: InpatientAdmissionRequestDto[] = [
  {
    id: 'req-001',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    requestNumber: 'REQ-ADM-2026-001',
    patientId: 'pat-003',
    patientName: 'Sarah Jenkins',
    patientMrn: 'MRN-2026-0219',
    referringDoctorName: 'Dr. Robert Chen, MD',
    admittingDoctorName: 'Dr. Amanda Sterling, MD (Pulmonology)',
    department: 'Pulmonology & Respiratory Care',
    specialty: 'Pulmonology',
    requestedWardType: 'GENERAL',
    requestedBedClass: 'GENERAL',
    admissionSource: 'OPD',
    priority: 'ROUTINE',
    isEmergency: false,
    provisionalDiagnosis: 'Severe Acute Exacerbation of COPD with hypercapnic respiratory fatigue',
    admissionReason: 'Requires IV bronchodilators, high-flow nasal cannula support, and close arterial blood gas monitoring.',
    expectedLengthOfStayDays: 4,
    insurancePreAuthRef: 'AUTH-PRE-9921',
    status: 'SUBMITTED',
    createdAt: '2026-08-29T08:30:00.000Z',
    updatedAt: '2026-08-29T08:30:00.000Z'
  },
  {
    id: 'req-002',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    requestNumber: 'REQ-ADM-2026-002',
    patientId: 'pat-004',
    patientName: 'David K. Miller',
    patientMrn: 'MRN-2026-0305',
    referringDoctorName: 'Dr. Gregory House, MD (ED Triage)',
    admittingDoctorName: 'Dr. Jonathan Reed, MD (Cardiology)',
    department: 'Critical Care Cardiology',
    specialty: 'Cardiology',
    requestedWardType: 'ICU',
    requestedBedClass: 'ICU',
    admissionSource: 'EMERGENCY',
    priority: 'STAT_EMERGENCY',
    isEmergency: true,
    provisionalDiagnosis: 'Non-ST Elevation Myocardial Infarction (NSTEMI) with hemodynamic instability',
    admissionReason: 'Emergency admission for continuous arterial line monitoring, heparin drip, and cardiac catheterization prep.',
    expectedLengthOfStayDays: 5,
    insurancePreAuthRef: 'EMERG-TPA-FAST-01',
    status: 'UNDER_REVIEW',
    createdAt: '2026-08-29T09:15:00.000Z',
    updatedAt: '2026-08-29T09:15:00.000Z'
  }
];

export const mockInpatientAdmissions: InpatientAdmissionDto[] = [
  {
    id: 'adm-001',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    admissionNumber: 'ADM-2026-0089',
    admissionRequestId: 'req-000',
    patientId: 'pat-001',
    patientName: 'Eleanor Vance',
    patientMrn: 'MRN-2026-0081',
    patientGender: 'Female',
    patientAge: 68,
    admittingDoctorName: 'Dr. Jonathan Reed, MD',
    attendingConsultantName: 'Dr. Jonathan Reed, MD (Chief of Cardiology)',
    department: 'Cardiovascular Surgery & ICU',
    specialty: 'Cardiology',
    wardId: 'ward-001',
    wardName: 'Intensive Care Unit (ICU Alpha)',
    bedId: 'bed-001',
    bedCode: 'ICU-BED-01',
    admissionType: 'EMERGENCY',
    admissionSource: 'EMERGENCY',
    admissionDateTime: '2026-08-26T14:20:00.000Z',
    expectedDischargeDate: '2026-08-31T12:00:00.000Z',
    primaryDiagnosis: 'Acute Decompensated Heart Failure with cardiogenic pulmonary edema (NYHA Class IV)',
    secondaryDiagnosis: 'Hypertensive Nephrosclerosis, Type 2 Diabetes Mellitus',
    isolationRequired: false,
    payerType: 'INSURANCE_TPA',
    payerName: 'Apex Health Shield Assurance (Payer TPA-101)',
    insuranceClaimNumber: 'CLM-IPD-2026-8812',
    financialDepositAmount: 1500.00,
    status: 'ADMITTED',
    dischargeSummaryFinalized: false,
    billingCleared: false,
    insuranceCleared: true,
    clinicalClearance: false,
    notes: 'Hemodynamically stabilized post-inotropic infusion. Stepdown to HDU/General floor planned.',
    createdAt: '2026-08-26T14:20:00.000Z',
    updatedAt: '2026-08-29T09:00:00.000Z'
  },
  {
    id: 'adm-002',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    admissionNumber: 'ADM-2026-0094',
    patientId: 'pat-002',
    patientName: 'Marcus Thorne',
    patientMrn: 'MRN-2026-0142',
    patientGender: 'Male',
    patientAge: 45,
    admittingDoctorName: 'Dr. Sarah Connor, MD',
    attendingConsultantName: 'Dr. Sarah Connor, MD (General & Laparoscopic Surgery)',
    department: 'General Surgery',
    specialty: 'Surgery',
    wardId: 'ward-002',
    wardName: 'General Medical Ward (4 East)',
    bedId: 'bed-003',
    bedCode: 'GM-401-A',
    admissionType: 'POST_OP',
    admissionSource: 'OPD',
    admissionDateTime: '2026-08-27T07:45:00.000Z',
    expectedDischargeDate: '2026-08-30T11:00:00.000Z',
    primaryDiagnosis: 'Post Laparoscopic Cholecystectomy (Acute Calculous Cholecystitis)',
    secondaryDiagnosis: 'Essential Hypertension',
    isolationRequired: false,
    payerType: 'CORPORATE_SPONSOR',
    payerName: 'MedTech Global Corporate Health Plan',
    insuranceClaimNumber: 'CORP-CLM-5502',
    financialDepositAmount: 500.00,
    status: 'DISCHARGE_PLANNED',
    dischargeSummaryFinalized: true,
    billingCleared: true,
    insuranceCleared: true,
    clinicalClearance: true,
    notes: 'Afebrile, surgical wounds clean and dry, oral tolerance 100%. Ready for routine home discharge.',
    createdAt: '2026-08-27T07:45:00.000Z',
    updatedAt: '2026-08-29T10:15:00.000Z'
  }
];

export const mockInpatientTransfers: InpatientTransferDto[] = [
  {
    id: 'trf-001',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    transferNumber: 'TRF-2026-0018',
    admissionId: 'adm-001',
    patientId: 'pat-001',
    patientName: 'Eleanor Vance',
    patientMrn: 'MRN-2026-0081',
    sourceWardId: 'ward-001',
    sourceWardName: 'Intensive Care Unit (ICU Alpha)',
    sourceBedId: 'bed-001',
    sourceBedCode: 'ICU-BED-01',
    destinationWardId: 'ward-002',
    destinationWardName: 'General Medical Ward (4 East)',
    destinationBedId: 'bed-004',
    destinationBedCode: 'GM-401-B',
    transferType: 'STEPDOWN',
    priority: 'ROUTINE',
    transferReason: 'Patient weaned off inotropes, stable rhythm; stepdown from ICU to General Medical floor.',
    requestingDoctorName: 'Dr. Jonathan Reed, MD',
    transportRequirement: 'WHEELCHAIR',
    nursingHandoffNotes: 'Arterial line removed. Peripheral IV line patent in left forearm. Oral medications restarted.',
    status: 'APPROVED',
    requestedAt: '2026-08-29T08:00:00.000Z',
    approvedAt: '2026-08-29T09:30:00.000Z',
    createdAt: '2026-08-29T08:00:00.000Z',
    updatedAt: '2026-08-29T09:30:00.000Z'
  }
];

export const mockInpatientNursingAssessments: InpatientNursingAssessmentDto[] = [
  {
    id: 'assess-001',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    admissionId: 'adm-001',
    patientId: 'pat-001',
    assessedBy: 'Senior Staff Nurse Patricia Bailey, RN',
    shiftType: 'MORNING_SHIFT',
    assessmentType: 'SHIFT_HANDOVER',
    fallRiskScore: 35,
    fallRiskLevel: 'MEDIUM',
    pressureInjuryRiskScore: 16,
    pressureInjuryRiskLevel: 'LOW',
    painScore: 2,
    consciousnessLevel: 'ALERT',
    mobilityStatus: 'ASSISTED_1_PERSON',
    dietaryIntakeLevel: 'DIABETIC_ORAL',
    nursingSummary: 'Patient alert and oriented x3. Bilateral air entry clear with minimal basal crackles. Foley catheter removed. Voiding clear urine spontaneously.',
    createdAt: '2026-08-29T07:30:00.000Z'
  }
];

export const mockInpatientVitalObservations: InpatientVitalObservationDto[] = [
  {
    id: 'vit-001',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    admissionId: 'adm-001',
    patientId: 'pat-001',
    recordedBy: "Nurse Kevin O'Connor, RN",
    temperatureCelsius: 36.8,
    pulseBpm: 72,
    respiratoryRateBpm: 16,
    systolicBpMmHg: 124,
    diastolicBpMmHg: 78,
    spo2Percentage: 97,
    bloodGlucoseMgDl: 118,
    painScaleScore: 1,
    gcsScore: 15,
    isAbnormal: false,
    notes: 'Hemodynamics stable on room air. Normal sinus rhythm on cardiac telemetry.',
    recordedAt: '2026-08-29T08:00:00.000Z'
  },
  {
    id: 'vit-002',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    admissionId: 'adm-002',
    patientId: 'pat-002',
    recordedBy: 'Nurse Emily Watson, RN',
    temperatureCelsius: 37.1,
    pulseBpm: 80,
    respiratoryRateBpm: 18,
    systolicBpMmHg: 130,
    diastolicBpMmHg: 84,
    spo2Percentage: 99,
    bloodGlucoseMgDl: 95,
    painScaleScore: 2,
    gcsScore: 15,
    isAbnormal: false,
    notes: 'Post-op Day 2. Patient ambulating well in corridor.',
    recordedAt: '2026-08-29T08:30:00.000Z'
  }
];

export const mockInpatientDoctorRounds: InpatientDoctorRoundDto[] = [
  {
    id: 'round-001',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    admissionId: 'adm-001',
    patientId: 'pat-001',
    doctorName: 'Dr. Jonathan Reed, MD',
    doctorSpecialty: 'Cardiovascular Medicine',
    roundType: 'MORNING_PRIMARY_ROUND',
    subjectiveAssessment: 'Patient reports no orthopnea, chest tightness, or palpitations overnight. Slept comfortably flat.',
    objectiveClinicalFindings: 'S1/S2 heard, no murmurs or gallop. JVP normal. Lungs clear. Trace ankle edema resolving.',
    clinicalImpression: 'Resolving Acute Decompensated Heart Failure; compensated state achieved.',
    treatmentPlanUpdates: 'Stepdown to oral Furosemide 40mg daily, continue Sacubitril/Valsartan 49/51mg BID. Transfer to General Floor.',
    orderedInvestigationsSummary: 'Serum Electrolytes, Renal Function Panel, NT-proBNP repeat on Monday.',
    dischargeReadinessScore: 80,
    expectedDischargeReviewDate: '2026-08-31T10:00:00.000Z',
    roundTimestamp: '2026-08-29T09:00:00.000Z'
  }
];

export const mockInpatientDischargePlans: InpatientDischargePlanDto[] = [
  {
    id: 'plan-001',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    admissionId: 'adm-002',
    patientId: 'pat-002',
    targetDischargeDate: '2026-08-30T11:00:00.000Z',
    readinessStatus: 'READY_FOR_DISCHARGE',
    isMedicationReconciled: true,
    isNursingCareHandoverDone: true,
    isBillingCleared: true,
    isInsurancePreApproved: true,
    isDischargeSummaryFinalized: true,
    transportArrangement: 'SELF_TRANSPORT',
    patientEducationSummary: 'Wound care instructions provided. Emphasized low-fat diet and avoiding heavy lifting for 2 weeks.',
    followUpInstructions: 'Surgical OPD follow-up on 2026-09-06 with Dr. Sarah Connor.',
    coordinatorName: 'Discharge Officer Laura Croft, RN',
    createdAt: '2026-08-29T09:00:00.000Z',
    updatedAt: '2026-08-29T10:00:00.000Z'
  }
];

export const mockInpatientDischargeSummaries: InpatientDischargeSummaryDto[] = [
  {
    id: 'sum-001',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    summaryNumber: 'DS-2026-0044',
    admissionId: 'adm-002',
    patientId: 'pat-002',
    patientName: 'Marcus Thorne',
    patientMrn: 'MRN-2026-0142',
    admissionDate: '2026-08-27T07:45:00.000Z',
    dischargeDate: '2026-08-30T11:00:00.000Z',
    attendingConsultantName: 'Dr. Sarah Connor, MD',
    finalPrimaryDiagnosis: 'Acute Calculous Cholecystitis (Status Post Elective Laparoscopic Cholecystectomy)',
    finalSecondaryDiagnosis: 'Essential Hypertension',
    surgicalProceduresPerformed: 'Laparoscopic 4-Port Cholecystectomy under General Anesthesia on 2026-08-27',
    hospitalCourseSummary: 'Patient admitted for elective cholecystectomy. Surgery uneventful with minimal blood loss. Postoperative recovery smooth, ambulating Day 1, tolerating regular oral diet.',
    keyInvestigationFindings: 'Histopathology: Chronic cholecystitis with cholelithiasis. No malignancy. Post-op LFTs normalized.',
    treatmentGiven: 'IV Cefazolin (pre-op), IV Paracetamol & Tramadol for analgesia, transitioned to oral analgesics.',
    dischargeMedicationAdvice: '1. Tab Paracetamol 1000mg TID PRN pain (5 days)\n2. Tab Pantoprazole 40mg once daily before breakfast (14 days)\n3. Resume regular Amlodipine 5mg daily for hypertension.',
    dietAndActivityAdvice: 'Low-fat regular diet, adequate hydration. Light walking encouraged. No heavy abdominal straining (>5kg) for 3 weeks.',
    warningSignsToSeekImmediateCare: 'Severe abdominal pain, persistent fever >38.5C, jaundice/yellowing of eyes, wound redness/discharge.',
    followUpAppointmentDate: '2026-09-06T10:00:00.000Z',
    followUpDoctorName: 'Dr. Sarah Connor, MD',
    isFinalized: true,
    finalizedBy: 'Dr. Sarah Connor, MD',
    finalizedAt: '2026-08-29T10:15:00.000Z',
    versionNumber: 1,
    createdAt: '2026-08-29T10:00:00.000Z',
    updatedAt: '2026-08-29T10:15:00.000Z'
  }
];

export const mockInpatientBedTurnarounds: InpatientBedTurnaroundDto[] = [
  {
    id: 'turn-001',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    turnaroundNumber: 'TRN-2026-0081',
    bedId: 'bed-004',
    bedCode: 'GM-401-B',
    wardId: 'ward-002',
    cleaningType: 'TERMINAL_DISCHARGE_DISINFECTION',
    requestedAt: '2026-08-29T09:30:00.000Z',
    assignedHousekeeper: 'Housekeeping Associate Carlos Gomez',
    cleaningStartedAt: '2026-08-29T09:40:00.000Z',
    status: 'IN_PROGRESS',
    environmentalInspectionPassed: false,
    notes: 'Terminal disinfection in progress after patient discharge.',
    createdAt: '2026-08-29T09:30:00.000Z',
    updatedAt: '2026-08-29T09:40:00.000Z'
  }
];

export const mockInpatientBedBlocks: InpatientBedBlockDto[] = [
  {
    id: 'block-001',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    blockNumber: 'BLK-2026-0012',
    bedId: 'bed-006',
    bedCode: 'DLX-502',
    wardId: 'ward-003',
    blockReason: 'BIOMEDICAL_MAINTENANCE',
    blockedFrom: '2026-08-28T08:00:00.000Z',
    authorizedBy: 'Biomedical Facility Supervisor Frank Castle',
    status: 'ACTIVE_BLOCKED',
    justificationNotes: 'Scheduled preventive maintenance and sensor calibration on automated high-spec ICU/Deluxe bed mechanism.',
    createdAt: '2026-08-28T08:00:00.000Z',
    updatedAt: '2026-08-28T08:00:00.000Z'
  }
];

export const mockInpatientAuditTraces: InpatientAuditTraceDto[] = [
  {
    id: 'trace-001',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    traceNumber: 'TRACE-IPD-00192',
    actorName: 'Dr. Jonathan Reed, MD',
    actorRole: 'ATTENDING_PHYSICIAN',
    action: 'ADMISSION_APPROVED',
    entityType: 'INPATIENT_ADMISSION',
    entityId: 'adm-001',
    entityCode: 'ADM-2026-0089',
    patientId: 'pat-001',
    patientMrn: 'MRN-2026-0081',
    newState: { status: 'ADMITTED', bedCode: 'ICU-BED-01' },
    justification: 'Emergency ICU bed allocation verified and authorized for critical cardiac monitoring.',
    ipAddress: '10.240.12.84',
    integrityHash: 'a8b9c0d1e2f3a4b5c6d7e8f90123456789abcdef0123456789abcdef01234567',
    previousHash: 'GENESIS_BLOCK_HASH_TRACE_000',
    timestamp: '2026-08-26T14:20:00.000Z'
  },
  {
    id: 'trace-002',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    traceNumber: 'TRACE-IPD-00193',
    actorName: 'Dr. Sarah Connor, MD',
    actorRole: 'ATTENDING_SURGEON',
    action: 'DISCHARGE_SUMMARY_FINALIZED',
    entityType: 'DISCHARGE_SUMMARY',
    entityId: 'sum-001',
    entityCode: 'DS-2026-0044',
    patientId: 'pat-002',
    patientMrn: 'MRN-2026-0142',
    newState: { isFinalized: true, versionNumber: 1 },
    justification: 'Postoperative laparoscopic cholecystectomy summary signed off with complete medication reconciliation.',
    ipAddress: '10.240.14.22',
    integrityHash: 'c9d8e7f6a5b4c3d2e1f0123456789abcdef0123456789abcdef0123456789ab',
    previousHash: 'a8b9c0d1e2f3a4b5c6d7e8f90123456789abcdef0123456789abcdef01234567',
    timestamp: '2026-08-29T10:15:00.000Z'
  }
];

export const mockInpatientOverviewMetrics: InpatientOverviewMetricsDto = {
  totalInpatients: 33,
  admissionsToday: 6,
  dischargesToday: 4,
  pendingAdmissions: 2,
  totalBeds: 46,
  availableBeds: 10,
  occupiedBeds: 33,
  reservedBeds: 1,
  blockedBeds: 1,
  cleaningBeds: 1,
  occupancyRatePercentage: 71.7,
  icuOccupancyRatePercentage: 75.0,
  averageLengthOfStayDays: 3.8,
  transferBacklog: 1,
  dischargeBacklog: 1,
  cleaningBacklog: 1,
  criticalAlertsCount: 2
};

export const mockInpatientAnalytics: InpatientAnalyticsDto = {
  wardOccupancy: [
    { wardName: 'ICU Alpha', totalBeds: 12, occupiedBeds: 9, rate: 75.0 },
    { wardName: 'General Med (4 East)', totalBeds: 24, occupiedBeds: 18, rate: 75.0 },
    { wardName: 'Deluxe Pavilion (5 West)', totalBeds: 10, occupiedBeds: 6, rate: 60.0 }
  ],
  dailyAdmissionDischargeTrends: [
    { date: '2026-08-23', admissions: 5, discharges: 3 },
    { date: '2026-08-24', admissions: 7, discharges: 4 },
    { date: '2026-08-25', admissions: 4, discharges: 6 },
    { date: '2026-08-26', admissions: 8, discharges: 5 },
    { date: '2026-08-27', admissions: 6, discharges: 7 },
    { date: '2026-08-28', admissions: 9, discharges: 4 },
    { date: '2026-08-29', admissions: 6, discharges: 4 }
  ],
  lengthOfStayDistribution: [
    { bracket: '1 - 2 Days (Observation/Day)', patientCount: 8 },
    { bracket: '3 - 5 Days (Routine Med/Surg)', patientCount: 19 },
    { bracket: '6 - 10 Days (Complex / Post-Op)', patientCount: 5 },
    { bracket: '> 10 Days (Long-Stay / ICU)', patientCount: 1 }
  ],
  careLevelUtilization: [
    { careLevel: 'Level 3 ICU', bedsCount: 12, activePatients: 9 },
    { careLevel: 'Level 2 Stepdown / HDU', bedsCount: 10, activePatients: 8 },
    { careLevel: 'Level 1 Observation / General', bedsCount: 24, activePatients: 16 }
  ]
};
