import type {
  OperationTheatreComplexDto,
  OperationTheatreRoomDto,
  SurgicalProcedureDto,
  SurgeryRequestDto,
  PreOperativeAssessmentDto,
  SurgicalConsentDto,
  OTScheduleDto,
  PreOpChecklistDto,
  SurgicalSafetyChecklistDto,
  OTTransferDto,
  AnaesthesiaRecordDto,
  IntraoperativeRecordDto,
  OperativeNoteDto,
  SurgicalSpecimenDto,
  SurgicalImplantDto,
  SurgicalConsumableUsageDto,
  PACURecoveryRecordDto,
  PostoperativeTransferDto,
  SurgeryCancellationDto,
  OTAuditTraceDto,
  OTOverviewMetricsDto,
  OTAnalyticsDto
} from '@docsearch/api-contracts';

const T_ID = '11111111-1111-4111-8111-111111111111';
const P_ID = '22222222-2222-4222-8222-222222222222';
const O_ID = '33333333-3333-4333-8333-333333333333';
const B_ID = '44444444-4444-4444-8444-444444444444';

export const mockOTComplexes: OperationTheatreComplexDto[] = [
  {
    id: 'otc-001',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    complexCode: 'OTC-MAIN',
    complexName: 'Main Surgical Pavilion Complex',
    building: 'Surgical Tower A',
    floor: 'Floor 2',
    headOfOT: 'Dr. Arthur Vance, MS (Gen Surg)',
    totalRooms: 8,
    activeRooms: 8,
    operatingHours: '24/7 (Emergency & Elective)',
    hasLaminarAirflow: true,
    hasCentralSterileSupply: true,
    isActive: true,
    createdAt: '2026-08-01T08:00:00.000Z',
    updatedAt: '2026-08-01T08:00:00.000Z'
  },
  {
    id: 'otc-002',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    complexCode: 'OTC-DAYCARE',
    complexName: 'Ambulatory & Daycare Surgery Center',
    building: 'Outpatient Pavilion B',
    floor: 'Floor 1',
    headOfOT: 'Dr. Rebecca Sterling, MD',
    totalRooms: 4,
    activeRooms: 4,
    operatingHours: '07:00 - 19:00',
    hasLaminarAirflow: true,
    hasCentralSterileSupply: true,
    isActive: true,
    createdAt: '2026-08-01T08:00:00.000Z',
    updatedAt: '2026-08-01T08:00:00.000Z'
  }
];

export const mockOTRooms: OperationTheatreRoomDto[] = [
  {
    id: 'otr-001',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    complexId: 'otc-001',
    complexName: 'Main Surgical Pavilion Complex',
    roomNumber: 'OT-01',
    roomName: 'Cardiothoracic & Vascular Suite',
    otType: 'CARDIAC_OT',
    status: 'OCCUPIED',
    primarySpecialty: 'CARDIOTHORACIC',
    supportedSpecialties: ['CARDIOTHORACIC', 'VASCULAR_SURGERY'],
    hasPendantSystem: true,
    hasCardiacMonitor: true,
    hasAnaesthesiaWorkstation: true,
    hasC臂Fluoroscopy: true,
    hasLaminarFlow: true,
    hasHepaFilter: true,
    lastCleanedAt: '2026-08-29T06:00:00.000Z',
    hourlyRate: 5000,
    isActive: true,
    currentSurgeryId: 'ots-001',
    currentPatientName: 'Robert Langdon',
    createdAt: '2026-08-01T08:00:00.000Z',
    updatedAt: '2026-08-01T08:00:00.000Z'
  },
  {
    id: 'otr-002',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    complexId: 'otc-001',
    complexName: 'Main Surgical Pavilion Complex',
    roomNumber: 'OT-02',
    roomName: 'Neurosurgery & Spine Suite',
    otType: 'NEUROSURGERY_OT',
    status: 'AVAILABLE',
    primarySpecialty: 'NEUROSURGERY',
    supportedSpecialties: ['NEUROSURGERY', 'ORTHOPAEDICS'],
    hasPendantSystem: true,
    hasCardiacMonitor: true,
    hasAnaesthesiaWorkstation: true,
    hasC臂Fluoroscopy: true,
    hasLaminarFlow: true,
    hasHepaFilter: true,
    lastCleanedAt: '2026-08-29T07:30:00.000Z',
    hourlyRate: 4500,
    isActive: true,
    createdAt: '2026-08-01T08:00:00.000Z',
    updatedAt: '2026-08-01T08:00:00.000Z'
  },
  {
    id: 'otr-003',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    complexId: 'otc-001',
    complexName: 'Main Surgical Pavilion Complex',
    roomNumber: 'OT-03',
    roomName: 'Orthopaedic & Joint Replacement Suite',
    otType: 'ORTHOPAEDIC_OT',
    status: 'RESERVED',
    primarySpecialty: 'ORTHOPAEDICS',
    supportedSpecialties: ['ORTHOPAEDICS', 'PLASTIC_RECONSTRUCTIVE'],
    hasPendantSystem: true,
    hasCardiacMonitor: true,
    hasAnaesthesiaWorkstation: true,
    hasC臂Fluoroscopy: true,
    hasLaminarFlow: true,
    hasHepaFilter: true,
    lastCleanedAt: '2026-08-29T08:00:00.000Z',
    hourlyRate: 3500,
    isActive: true,
    createdAt: '2026-08-01T08:00:00.000Z',
    updatedAt: '2026-08-01T08:00:00.000Z'
  },
  {
    id: 'otr-004',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    complexId: 'otc-001',
    complexName: 'Main Surgical Pavilion Complex',
    roomNumber: 'OT-04',
    roomName: 'Emergency & Trauma Surgical Suite',
    otType: 'EMERGENCY_OT',
    status: 'AVAILABLE',
    primarySpecialty: 'GENERAL_SURGERY',
    supportedSpecialties: ['GENERAL_SURGERY', 'ORTHOPAEDICS', 'VASCULAR_SURGERY'],
    hasPendantSystem: true,
    hasCardiacMonitor: true,
    hasAnaesthesiaWorkstation: true,
    hasC臂Fluoroscopy: true,
    hasLaminarFlow: true,
    hasHepaFilter: true,
    lastCleanedAt: '2026-08-29T05:00:00.000Z',
    hourlyRate: 4000,
    isActive: true,
    createdAt: '2026-08-01T08:00:00.000Z',
    updatedAt: '2026-08-01T08:00:00.000Z'
  },
  {
    id: 'otr-005',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    complexId: 'otc-001',
    complexName: 'Main Surgical Pavilion Complex',
    roomNumber: 'OT-05',
    roomName: 'Laparoscopy & General Surgery Suite',
    otType: 'MAJOR_OT',
    status: 'CLEANING',
    primarySpecialty: 'GENERAL_SURGERY',
    supportedSpecialties: ['GENERAL_SURGERY', 'SURGICAL_ONCOLOGY', 'UROLOGY'],
    hasPendantSystem: true,
    hasCardiacMonitor: true,
    hasAnaesthesiaWorkstation: true,
    hasC臂Fluoroscopy: false,
    hasLaminarFlow: true,
    hasHepaFilter: true,
    lastCleanedAt: '2026-08-29T09:15:00.000Z',
    hourlyRate: 3000,
    isActive: true,
    createdAt: '2026-08-01T08:00:00.000Z',
    updatedAt: '2026-08-01T08:00:00.000Z'
  }
];

export const mockSurgicalProcedures: SurgicalProcedureDto[] = [
  {
    id: 'prc-001',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    procedureCode: 'PRC-CABG',
    procedureName: 'Coronary Artery Bypass Grafting (CABG x3)',
    specialty: 'CARDIOTHORACIC',
    category: 'MAJOR_PROCEDURE',
    defaultDurationMinutes: 240,
    recommendedAnaesthesia: 'GENERAL_ANAESTHESIA',
    requiresImplant: true,
    requiresBloodCrossmatch: true,
    requiresICUStay: true,
    baseProcedureCharge: 185000,
    cptOrIcdCode: '33533',
    isActive: true,
    createdAt: '2026-08-01T08:00:00.000Z',
    updatedAt: '2026-08-01T08:00:00.000Z'
  },
  {
    id: 'prc-002',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    procedureCode: 'PRC-TKR',
    procedureName: 'Total Knee Replacement (Right)',
    specialty: 'ORTHOPAEDICS',
    category: 'MAJOR_PROCEDURE',
    defaultDurationMinutes: 120,
    recommendedAnaesthesia: 'SPINAL_ANAESTHESIA',
    requiresImplant: true,
    requiresBloodCrossmatch: true,
    requiresICUStay: false,
    baseProcedureCharge: 125000,
    cptOrIcdCode: '27447',
    isActive: true,
    createdAt: '2026-08-01T08:00:00.000Z',
    updatedAt: '2026-08-01T08:00:00.000Z'
  },
  {
    id: 'prc-003',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    procedureCode: 'PRC-LAP-CHOL',
    procedureName: 'Laparoscopic Cholecystectomy',
    specialty: 'GENERAL_SURGERY',
    category: 'ELECTIVE',
    defaultDurationMinutes: 75,
    recommendedAnaesthesia: 'GENERAL_ANAESTHESIA',
    requiresImplant: false,
    requiresBloodCrossmatch: false,
    requiresICUStay: false,
    baseProcedureCharge: 45000,
    cptOrIcdCode: '47562',
    isActive: true,
    createdAt: '2026-08-01T08:00:00.000Z',
    updatedAt: '2026-08-01T08:00:00.000Z'
  },
  {
    id: 'prc-004',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    procedureCode: 'PRC-EMERG-APP',
    procedureName: 'Emergency Laparoscopic Appendectomy',
    specialty: 'GENERAL_SURGERY',
    category: 'EMERGENCY',
    defaultDurationMinutes: 60,
    recommendedAnaesthesia: 'GENERAL_ANAESTHESIA',
    requiresImplant: false,
    requiresBloodCrossmatch: false,
    requiresICUStay: false,
    baseProcedureCharge: 38000,
    cptOrIcdCode: '44970',
    isActive: true,
    createdAt: '2026-08-01T08:00:00.000Z',
    updatedAt: '2026-08-01T08:00:00.000Z'
  }
];

export const mockSurgeryRequests: SurgeryRequestDto[] = [
  {
    id: 'req-001',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    requestNumber: 'REQ-SURG-001',
    patientId: 'pat-101',
    patientName: 'Robert Langdon',
    patientMrn: 'MRN-882190',
    patientAge: 58,
    patientGender: 'M',
    encounterId: 'enc-201',
    admissionId: 'adm-301',
    requestingDoctorName: 'Dr. Sarah Connor, MD',
    primarySurgeonName: 'Dr. Gregory House, MS (CTVS)',
    specialty: 'CARDIOTHORACIC',
    procedureId: 'prc-001',
    procedureName: 'Coronary Artery Bypass Grafting (CABG x3)',
    preOperativeDiagnosis: 'Triple Vessel Coronary Artery Disease with unstable angina',
    clinicalIndication: 'Severe LAD and RCA stenosis > 85%',
    category: 'MAJOR_PROCEDURE',
    priority: 'URGENT',
    isEmergency: false,
    proposedSurgeryDate: '2026-08-30T09:00:00.000Z',
    estimatedDurationMinutes: 240,
    requiredAnaesthesia: 'GENERAL_ANAESTHESIA',
    implantRequirementDetails: 'Cardiovascular prosthetic graft conduits, vascular clips',
    bloodComponentsRequired: '4 Units PRBC, 2 Units FFP',
    specialEquipmentRequired: 'Heart-Lung Machine (CPB Console), ACT Machine',
    pacClearanceStatus: 'CLEARED',
    status: 'SCHEDULED',
    decisionNotes: 'PAC Cleared, high cardiac risk noted, ICU bed reserved',
    createdAt: '2026-08-28T10:00:00.000Z',
    updatedAt: '2026-08-28T11:30:00.000Z'
  },
  {
    id: 'req-002',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    requestNumber: 'REQ-SURG-002',
    patientId: 'pat-102',
    patientName: 'Eleanor Vance',
    patientMrn: 'MRN-991204',
    patientAge: 64,
    patientGender: 'F',
    encounterId: 'enc-202',
    admissionId: 'adm-302',
    requestingDoctorName: 'Dr. Michael Chang, MS',
    primarySurgeonName: 'Dr. Michael Chang, MS (Ortho)',
    specialty: 'ORTHOPAEDICS',
    procedureId: 'prc-002',
    procedureName: 'Total Knee Replacement (Right)',
    preOperativeDiagnosis: 'Grade IV Primary Osteoarthritis Right Knee',
    clinicalIndication: 'Severe pain, joint space narrowing, failed conservative therapy',
    category: 'MAJOR_PROCEDURE',
    priority: 'ROUTINE',
    isEmergency: false,
    proposedSurgeryDate: '2026-08-30T11:00:00.000Z',
    estimatedDurationMinutes: 120,
    requiredAnaesthesia: 'SPINAL_ANAESTHESIA',
    implantRequirementDetails: 'Modular TKR Implant Kit (Femoral, Tibial Tray, Poly Insert)',
    bloodComponentsRequired: '2 Units PRBC cross-matched',
    specialEquipmentRequired: 'Pneumatic Tourniquet, Ortho C-Arm, Bone Cement Mixer',
    pacClearanceStatus: 'CLEARED',
    status: 'APPROVED',
    decisionNotes: 'Approved for OT-03 elective schedule',
    createdAt: '2026-08-28T14:00:00.000Z',
    updatedAt: '2026-08-28T15:00:00.000Z'
  },
  {
    id: 'req-003',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    requestNumber: 'REQ-SURG-003',
    patientId: 'pat-103',
    patientName: 'Arthur Dent',
    patientMrn: 'MRN-442110',
    patientAge: 42,
    patientGender: 'M',
    requestingDoctorName: 'Dr. Rajesh Rao, MS',
    primarySurgeonName: 'Dr. Rajesh Rao, MS',
    specialty: 'GENERAL_SURGERY',
    procedureId: 'prc-003',
    procedureName: 'Laparoscopic Cholecystectomy',
    preOperativeDiagnosis: 'Symptomatic Cholelithiasis with Chronic Cholecystitis',
    clinicalIndication: 'Recurrent biliary colic, multiple gallbladder calculi on USG',
    category: 'ELECTIVE',
    priority: 'ROUTINE',
    isEmergency: false,
    proposedSurgeryDate: '2026-08-31T08:30:00.000Z',
    estimatedDurationMinutes: 75,
    requiredAnaesthesia: 'GENERAL_ANAESTHESIA',
    bloodComponentsRequired: 'Routine standby',
    pacClearanceStatus: 'IN_PROGRESS',
    status: 'SUBMITTED',
    createdAt: '2026-08-29T08:00:00.000Z',
    updatedAt: '2026-08-29T08:00:00.000Z'
  }
];

export const mockPreOpAssessments: PreOperativeAssessmentDto[] = [
  {
    id: 'pac-001',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    surgeryRequestId: 'req-001',
    patientId: 'pat-101',
    patientName: 'Robert Langdon',
    assessedByAnaesthetist: 'Dr. Christopher Nolan, MD (Anaesth)',
    assessmentDate: '2026-08-28T11:00:00.000Z',
    asaClassification: 'ASA_III_SEVERE_SYSTEMIC_DISEASE',
    airwayMallampatiScore: 2,
    npoStatusHours: 8,
    cardiacClearanceGiven: true,
    respiratoryClearanceGiven: true,
    allergiesNoted: 'Penicillin (mild cutaneous rash)',
    currentMedicationsNoted: 'Aspirin, Atorvastatin, Metoprolol',
    lastHaemoglobinGdl: 13.4,
    coagulationProfileStatus: 'PT/INR: 1.1 (Within limits)',
    bloodArrangementUnits: 4,
    fitnessStatus: 'CLEARED',
    anaesthesiaPlanNotes: 'General endotracheal anaesthesia with invasive arterial line and central venous pressure monitoring',
    riskFactorsSummary: 'Controlled Hypertension, High cardiac risk, Mallampati Class II',
    createdAt: '2026-08-28T11:00:00.000Z',
    updatedAt: '2026-08-28T11:00:00.000Z'
  }
];

export const mockSurgicalConsents: SurgicalConsentDto[] = [
  {
    id: 'cns-001',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    surgeryRequestId: 'req-001',
    patientId: 'pat-101',
    patientName: 'Robert Langdon',
    consentNumber: 'CNS-2026-001',
    procedureConsentGiven: true,
    anaesthesiaConsentGiven: true,
    bloodTransfusionConsentGiven: true,
    highRiskConsentGiven: true,
    implantConsentGiven: true,
    consentingPersonName: 'Robert Langdon',
    relationshipToPatient: 'SELF',
    counselledByDoctor: 'Dr. Gregory House, MS',
    witnessName: 'Nurse Jennifer Adams',
    isSignedDigitally: true,
    consentTimestamp: '2026-08-28T16:00:00.000Z',
    status: 'VALID_SIGNED',
    notes: 'Risks including perioperative myocardial infarction, bleeding, and sternal infection fully explained and understood.',
    createdAt: '2026-08-28T16:00:00.000Z'
  }
];

export const mockOTSchedules: OTScheduleDto[] = [
  {
    id: 'ots-001',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    scheduleNumber: 'SCH-OT-001',
    surgeryRequestId: 'req-001',
    patientId: 'pat-101',
    patientName: 'Robert Langdon',
    patientMrn: 'MRN-882190',
    procedureName: 'Coronary Artery Bypass Grafting (CABG x3)',
    roomId: 'otr-001',
    roomName: 'Cardiothoracic & Vascular Suite (OT-01)',
    scheduledDate: '2026-08-30T09:00:00.000Z',
    startTime: '2026-08-30T09:00:00.000Z',
    endTime: '2026-08-30T13:00:00.000Z',
    estimatedDurationMinutes: 240,
    primarySurgeonName: 'Dr. Gregory House',
    assistantSurgeonName: 'Dr. Allison Cameron',
    leadAnaesthetistName: 'Dr. Christopher Nolan',
    anaesthesiaTechName: 'Tech Rahul Sharma',
    scrubNurseName: 'Nurse Jennifer Adams',
    circulatingNurseName: 'Nurse Priya Singh',
    isEmergency: false,
    status: 'CONFIRMED',
    createdAt: '2026-08-28T17:00:00.000Z',
    updatedAt: '2026-08-28T17:00:00.000Z'
  }
];

export const mockPreOpChecklists: PreOpChecklistDto[] = [
  {
    id: 'pck-001',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    scheduleId: 'ots-001',
    patientId: 'pat-101',
    verifiedByNurse: 'Nurse Jennifer Adams',
    patientIdentityVerified: true,
    surgicalSiteMarked: true,
    consentVerified: true,
    npoVerified: true,
    allergiesChecked: true,
    preOpVitalsChecked: true,
    labReportsAvailable: true,
    imagingAvailable: true,
    bloodReservedAndChecked: true,
    implantsVerifiedInOT: true,
    denturesJewelryRemoved: true,
    preMedicationAdministered: true,
    isClearedForOT: true,
    notes: 'Pre-op checklist complete; patient ready for transfer to OT-01',
    completedAt: '2026-08-30T08:15:00.000Z'
  }
];

export const mockSurgicalSafetyChecklists: SurgicalSafetyChecklistDto[] = [
  {
    id: 'ssc-001',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    scheduleId: 'ots-001',
    patientId: 'pat-101',
    stage: 'SIGN_IN',
    conductedBy: 'Nurse Priya Singh',
    conductedRole: 'CIRCULATING_NURSE',
    patientConfirmed: true,
    siteMarkingConfirmed: true,
    anaesthesiaMachineChecked: true,
    pulseOximeterFunctioning: true,
    knownAllergyConfirmed: true,
    difficultAirwayRiskEvaluated: true,
    bloodLossRiskEvaluated: true,
    teamIntroducedRoles: true,
    antibioticProphylaxisGiven: true,
    essentialImagingDisplayed: true,
    spongeCountCorrect: true,
    needleCountCorrect: true,
    instrumentCountCorrect: true,
    specimenProperlyLabeled: true,
    equipmentIssuesIdentified: false,
    recoveryConcernsAddressed: true,
    timestamp: '2026-08-30T08:45:00.000Z'
  }
];

export const mockOTTransfers: OTTransferDto[] = [
  {
    id: 'trf-001',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    transferNumber: 'TRF-OT-001',
    scheduleId: 'ots-001',
    patientId: 'pat-101',
    patientName: 'Robert Langdon',
    sourceLocation: 'ICU Bed 04',
    destinationRoomId: 'otr-001',
    destinationRoomName: 'OT-01 (Cardiothoracic Suite)',
    transportStaffName: 'Orderly Ramesh Kumar',
    handoverGivenBy: 'Staff Nurse Sunita',
    handoverReceivedBy: 'Nurse Jennifer Adams',
    departureTime: '2026-08-30T08:25:00.000Z',
    arrivalTime: '2026-08-30T08:35:00.000Z',
    patientConditionOnArrival: 'STABLE_CONSCIOUS',
    status: 'COMPLETED',
    createdAt: '2026-08-30T08:25:00.000Z'
  }
];

export const mockAnaesthesiaRecords: AnaesthesiaRecordDto[] = [
  {
    id: 'ans-001',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    scheduleId: 'ots-001',
    patientId: 'pat-101',
    leadAnaesthetist: 'Dr. Christopher Nolan',
    anaesthesiaType: 'GENERAL_ANAESTHESIA',
    inductionTime: '2026-08-30T08:50:00.000Z',
    intubationDetails: '7.5mm cuffed endotracheal tube under direct laryngoscopy (Cormack-Lehane Grade 1)',
    airwayDeviceUsed: 'ENDOTRACHEAL_TUBE',
    administeredAgentsSummary: 'Propofol, Fentanyl, Rocuronium, Sevoflurane in O2/Air mixture',
    ivFluidsAdministeredMl: 1500,
    bloodTransfusedUnits: 2,
    estimatedIntraopBloodLossMl: 250,
    intraopVitalsStability: 'HEMODYNAMICALLY_STABLE',
    postAnaesthesiaAldreteScore: 9,
    createdAt: '2026-08-30T08:50:00.000Z'
  }
];

export const mockIntraoperativeRecords: IntraoperativeRecordDto[] = [
  {
    id: 'iop-001',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    scheduleId: 'ots-001',
    patientId: 'pat-101',
    patientName: 'Robert Langdon',
    procedureName: 'Coronary Artery Bypass Grafting (CABG x3)',
    primarySurgeon: 'Dr. Gregory House',
    assistantSurgeon: 'Dr. Allison Cameron',
    scrubNurse: 'Nurse Jennifer Adams',
    circulatingNurse: 'Nurse Priya Singh',
    incisionTime: '2026-08-30T09:15:00.000Z',
    surgicalApproach: 'Median sternotomy with cardiopulmonary bypass',
    intraoperativeFindings: 'LAD severely calcified (90%), OM1 subtotal occlusion, RCA 80% stenosis. Good distal targets.',
    procedureDetails: 'LIMA harvested and anastomosed to LAD. SVG harvested and bypassed to OM1 and RCA. Off CPB smoothly on low dose Inotropes.',
    specimensCollectedCount: 1,
    implantsPlacedCount: 2,
    spongeCountVerified: true,
    needleCountVerified: true,
    instrumentCountVerified: true,
    drainsPlaced: 'Two chest tubes (Mediastinal and Pleural)',
    closureTechnique: 'Stainless steel sternal wire cerclage; subcutaneous layered closure with Monocryl',
    patientConditionPostSurgery: 'STABLE_INTUBATED',
    status: 'IN_PROGRESS',
    createdAt: '2026-08-30T09:15:00.000Z',
    updatedAt: '2026-08-30T11:00:00.000Z'
  }
];

export const mockOperativeNotes: OperativeNoteDto[] = [
  {
    id: 'opn-001',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    scheduleId: 'ots-001',
    noteNumber: 'OPN-2026-001',
    patientId: 'pat-101',
    patientName: 'Robert Langdon',
    patientMrn: 'MRN-882190',
    primarySurgeonName: 'Dr. Gregory House',
    preOperativeDiagnosis: 'Triple Vessel Coronary Artery Disease',
    postOperativeDiagnosis: 'Status post CABG x3 (LIMA-LAD, SVG-OM1, SVG-RCA) on CPB',
    procedurePerformedTitle: 'Coronary Artery Bypass Grafting (x3 grafts)',
    detailedOperativeFindings: 'Left Internal Mammary Artery excellent flow. Saphenous vein grafts pliable. Myocardial revascularization complete.',
    operativeTechniqueStepByStep: '1. Standard median sternotomy. 2. Heparinization & aortic/venous cannulation. 3. Cold blood cardioplegia arrest. 4. Distal and proximal anastomoses constructed. 5. Sternal closure with 6 wires.',
    estimatedBloodLossMl: 250,
    tissueSpecimensSentForBiopsy: 'Segments of SVG and excised perivascular fat',
    prosthesisAndImplantsUsed: 'Sternal Wire Cerclage Kit (Size 5)',
    postOperativeInstructions: 'Transfer intubated to CTVS ICU. Keep on ventilator support. Monitor chest tube outputs q1h. Target MAP 75-85 mmHg.',
    isFinalized: true,
    finalizedBy: 'Dr. Gregory House',
    finalizedAt: '2026-08-30T13:30:00.000Z',
    versionNumber: 1,
    createdAt: '2026-08-30T13:30:00.000Z',
    updatedAt: '2026-08-30T13:30:00.000Z'
  }
];

export const mockSurgicalSpecimens: SurgicalSpecimenDto[] = [
  {
    id: 'spc-001',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    specimenNumber: 'SPC-SURG-001',
    scheduleId: 'ots-001',
    patientId: 'pat-101',
    patientName: 'Robert Langdon',
    anatomicOriginSite: 'Aortic valve calcification / Perivascular tissue',
    specimenDescription: 'Firm, yellowish calcified plaque and tissue fragments',
    fixativeUsed: '10% BUFFERED FORMALIN',
    orderedInvestigation: 'Histopathology and Calcification Morphology',
    destinationLab: 'HISTOPATHOLOGY_LAB',
    collectedBySurgeon: 'Dr. Gregory House',
    collectionTime: '2026-08-30T10:45:00.000Z',
    labelVerifiedByNurse: 'Nurse Priya Singh',
    labHandoverStatus: 'RECEIVED_IN_LAB',
    labReceivedAt: '2026-08-30T11:15:00.000Z',
    createdAt: '2026-08-30T10:45:00.000Z'
  }
];

export const mockSurgicalImplants: SurgicalImplantDto[] = [
  {
    id: 'imp-001',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    implantTrackingNumber: 'IMP-2026-0089',
    scheduleId: 'ots-001',
    patientId: 'pat-101',
    patientName: 'Robert Langdon',
    implantName: 'Sternal Wire Cerclage Kit (Size 5)',
    implantType: 'STERNAL_CLOSURE_SYSTEM',
    manufacturerName: 'Ethicon / Johnson & Johnson',
    modelNumber: 'SW-500',
    serialOrLotNumber: 'LOT-98721',
    udiBarcode: '(01)0088921001(17)280831(10)LOT-98721',
    anatomicPlacementSite: 'Mid-sternal junction',
    implantedBySurgeon: 'Dr. Gregory House',
    implantTimestamp: '2026-08-30T12:15:00.000Z',
    supplierOrVendor: 'Apex Surgical Technologies',
    unitCost: 14500,
    status: 'IMPLANTED',
    createdAt: '2026-08-30T12:15:00.000Z'
  }
];

export const mockSurgicalConsumables: SurgicalConsumableUsageDto[] = [
  {
    id: 'csm-001',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    scheduleId: 'ots-001',
    patientId: 'pat-101',
    itemCode: 'CSM-PROLENE-7-0',
    itemName: 'Prolene 7-0 Double Armed Hemopack Suture',
    batchNumber: 'BATCH-2026-PRL',
    quantityUsed: 4,
    unitOfMeasure: 'PACK',
    unitPrice: 1200,
    totalCost: 4800,
    recordedBy: 'Nurse Jennifer Adams',
    inventoryDeductionStatus: 'DEDUCTED',
    usedAt: '2026-08-30T10:00:00.000Z'
  }
];

export const mockPACURecords: PACURecoveryRecordDto[] = [
  {
    id: 'pcu-001',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    scheduleId: 'ots-001',
    patientId: 'pat-101',
    patientName: 'Robert Langdon',
    patientMrn: 'MRN-882190',
    recoveryBedNumber: 'PACU-BED-02',
    pacuNurseName: 'Nurse David Miller',
    arrivalTime: '2026-08-30T13:15:00.000Z',
    initialAldreteScore: 8,
    currentAldreteScore: 9,
    consciousnessLevel: 'AROUSABLE_TO_VOICE',
    airwayStatus: 'ENDOTRACHEAL_INTUBATED',
    oxygenSupportLpm: 4,
    spo2Percentage: 99,
    systolicBpMmHg: 124,
    diastolicBpMmHg: 78,
    heartRateBpm: 72,
    painScoreNumeric: 2,
    nauseaVomitingStatus: 'NONE',
    woundDrainOutputMl: 30,
    status: 'RECOVERING',
    dischargeCriteriaMet: true,
    authorizedTransferDestination: 'CARDIOTHORACIC_ICU',
    createdAt: '2026-08-30T13:15:00.000Z',
    updatedAt: '2026-08-30T14:00:00.000Z'
  }
];

export const mockPostoperativeTransfers: PostoperativeTransferDto[] = [
  {
    id: 'ptr-001',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    transferNumber: 'PTR-2026-001',
    scheduleId: 'ots-001',
    patientId: 'pat-101',
    patientName: 'Robert Langdon',
    originLocation: 'PACU Recovery Bay 2',
    destinationWardOrICU: 'CTVS Intensive Care Unit (ICU-A)',
    destinationBedNumber: 'ICU-BED-01',
    transferringNurse: 'Nurse David Miller',
    receivingNurse: 'ICU Nurse Clara Oswald',
    clinicalConditionSummary: 'Hemodynamically stable on low dose Inotropes; drains functioning normally',
    transferTime: '2026-08-30T14:15:00.000Z',
    status: 'COMPLETED',
    createdAt: '2026-08-30T14:15:00.000Z'
  }
];

export const mockSurgeryCancellations: SurgeryCancellationDto[] = [
  {
    id: 'cnl-001',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    cancellationNumber: 'CNL-2026-001',
    scheduleId: 'ots-001',
    patientId: 'pat-104',
    patientName: 'Samuel Jackson',
    procedureName: 'Elective Inguinal Hernioplasty',
    cancellationReason: 'Patient presented with acute URI and productive cough on morning of surgery',
    cancelledBy: 'Dr. Christopher Nolan',
    cancelledByRole: 'LEAD_ANAESTHETIST',
    reschedulingRequested: true,
    notes: 'Reschedule after 2 weeks of antibiotic course and symptom resolution.',
    cancelledAt: '2026-08-28T08:00:00.000Z'
  }
];

export const mockOTAuditTraces: OTAuditTraceDto[] = [
  {
    id: 'aud-001',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    traceNumber: 'TRACE-OT-00892101',
    actorId: 'usr-surgeon-01',
    actorName: 'Dr. Gregory House',
    actorRole: 'PRIMARY_SURGEON',
    action: 'START_SURGERY',
    entityType: 'INTRAOPERATIVE_RECORD',
    entityId: 'iop-001',
    entityCode: 'SCH-OT-001',
    justification: 'Incision made under full aseptic precautions after WHO Sign-In',
    ipAddress: '10.0.4.12',
    integrityHash: 'sha256-8f921bc4e08a892b11293a',
    newState: { status: 'IN_PROGRESS' },
    previousHash: 'sha256-genesis',
    timestamp: '2026-08-30T09:15:00.000Z'
  },
  {
    id: 'aud-002',
    tenantId: T_ID,
    partnerId: P_ID,
    organizationId: O_ID,
    branchId: B_ID,
    traceNumber: 'TRACE-OT-00892102',
    actorId: 'usr-nurse-01',
    actorName: 'Nurse Priya Singh',
    actorRole: 'CIRCULATING_NURSE',
    action: 'COMPLETE_SAFETY_CHECKLIST',
    entityType: 'WHO_SURGICAL_SAFETY',
    entityId: 'ssc-001',
    entityCode: 'SCH-OT-001',
    justification: 'WHO Sign-In checks confirmed and signed',
    ipAddress: '10.0.4.15',
    integrityHash: 'sha256-11bfa8290ce4a7192bc',
    newState: { stage: 'SIGN_IN', status: 'VERIFIED' },
    previousHash: 'sha256-8f921bc4e08a892b11293a',
    timestamp: '2026-08-30T08:45:00.000Z'
  }
];

export const mockOTOverviewMetrics: OTOverviewMetricsDto = {
  totalOTRooms: 5,
  activeOTRooms: 5,
  occupiedOTRooms: 2,
  availableOTRooms: 2,
  surgeriesToday: 6,
  completedSurgeriesToday: 3,
  inProgressSurgeries: 1,
  emergencySurgeriesToday: 1,
  pendingRequests: 4,
  pacuPatientsCount: 1,
  otUtilizationPercentage: 82.5,
  delayedSurgeriesCount: 0,
  averageTurnaroundTimeMinutes: 28
};

export const mockOTAnalytics: OTAnalyticsDto = {
  specialtyDistribution: [
    { specialty: 'General Surgery', caseCount: 48, utilizationPercentage: 35 },
    { specialty: 'Orthopaedics', caseCount: 36, utilizationPercentage: 26 },
    { specialty: 'Cardiothoracic', caseCount: 22, utilizationPercentage: 18 },
    { specialty: 'Neurosurgery', caseCount: 14, utilizationPercentage: 11 },
    { specialty: 'Obstetrics & Gynaecology', caseCount: 12, utilizationPercentage: 10 }
  ],
  monthlySurgeryTrends: [
    { month: 'Apr 2026', electiveCount: 95, emergencyCount: 18 },
    { month: 'May 2026', electiveCount: 110, emergencyCount: 22 },
    { month: 'Jun 2026', electiveCount: 124, emergencyCount: 19 },
    { month: 'Jul 2026', electiveCount: 138, emergencyCount: 25 },
    { month: 'Aug 2026', electiveCount: 142, emergencyCount: 21 }
  ],
  turnaroundTimeByRoom: [
    { roomName: 'OT-01 (Cardiac)', avgTurnaroundMinutes: 32 },
    { roomName: 'OT-02 (Neuro)', avgTurnaroundMinutes: 30 },
    { roomName: 'OT-03 (Ortho)', avgTurnaroundMinutes: 25 },
    { roomName: 'OT-04 (Emergency)', avgTurnaroundMinutes: 18 },
    { roomName: 'OT-05 (General)', avgTurnaroundMinutes: 22 }
  ],
  cancellationReasons: [
    { reason: 'Patient acute respiratory infection / Fever', count: 5 },
    { reason: 'Patient non-adherence to NPO instructions', count: 3 },
    { reason: 'Emergency case priority pre-emption', count: 2 },
    { reason: 'Elevated blood pressure / Cardiac review pending', count: 2 }
  ]
};
