/**
 * DOC SEARCH Partner Platform - PWA Companion & Installation Engine
 *
 * Provides:
 * - 1-Click PWA Installation across Android, iOS, Windows, Mac
 * - Standalone display-mode detection
 * - Offline/Online network health monitor with active ping probe
 * - Service Worker lifecycle management and auto-updating via Workbox
 */

export interface PwaState {
  isInstallable: boolean;
  isStandalone: boolean;
  isInstalled: boolean;
  isOnline: boolean;
  isServiceWorkerReady: boolean;
  hasUpdateAvailable: boolean;
}

export type PwaListener = (state: PwaState) => void;

class PwaCompanion {
  private deferredInstallPrompt: any = null;
  private listeners: Set<PwaListener> = new Set();
  private registration: ServiceWorkerRegistration | null = null;
  private pingInterval: any = null;

  private state: PwaState = {
    isInstallable: false,
    isStandalone: false,
    isInstalled: false,
    isOnline: typeof navigator !== 'undefined' ? navigator.onLine : true,
    isServiceWorkerReady: false,
    hasUpdateAvailable: false
  };

  constructor() {
    if (typeof window === 'undefined') return;

    // 1. Standalone detection (PWA mode)
    const isStandaloneMode =
      window.matchMedia('(display-mode: standalone)').matches ||
      (navigator as any).standalone === true ||
      document.referrer.includes('android-app://');

    this.state.isStandalone = isStandaloneMode;
    if (isStandaloneMode) {
      this.state.isInstalled = true;
    }

    // 2. Capture beforeinstallprompt (Chromium / Edge / Android)
    window.addEventListener('beforeinstallprompt', (e) => {
      e.preventDefault();
      this.deferredInstallPrompt = e;
      this.updateState({ isInstallable: true });
      console.log('[PWA] beforeinstallprompt captured - ready for 1-click install.');
    });

    // 3. Listen for appinstalled
    window.addEventListener('appinstalled', () => {
      this.deferredInstallPrompt = null;
      this.updateState({
        isInstallable: false,
        isInstalled: true
      });
      console.log('[PWA] Application successfully installed.');
    });

    // 4. Online/offline events
    window.addEventListener('online', () => {
      this.verifyActualConnectivity();
    });

    window.addEventListener('offline', () => {
      this.updateState({ isOnline: false });
    });

    // 5. Periodic active health probe (every 25 seconds) to detect silent network drops
    this.pingInterval = setInterval(() => {
      if (document.visibilityState === 'visible') {
        this.verifyActualConnectivity();
      }
    }, 25000);
  }

  /**
   * Register modern service worker generated by VitePWA
   */
  public async registerServiceWorker(): Promise<void> {
    if (typeof window === 'undefined' || !('serviceWorker' in navigator)) {
      return;
    }

    try {
      this.registration = await navigator.serviceWorker.register('/sw.js', {
        scope: '/'
      });

      this.updateState({ isServiceWorkerReady: true });
      console.log('[PWA] Service Worker registered with scope:', this.registration.scope);

      // Check for updates
      this.registration.onupdatefound = () => {
        const installingWorker = this.registration?.installing;
        if (installingWorker) {
          installingWorker.onstatechange = () => {
            if (installingWorker.state === 'installed' && navigator.serviceWorker.controller) {
              console.log('[PWA] New version ready for activation.');
              this.updateState({ hasUpdateAvailable: true });
            }
          };
        }
      };
    } catch (err) {
      console.warn('[PWA] Service worker registration notice:', err);
    }
  }

  /**
   * Proactively ping backend to distinguish genuine internet connection from captive portals
   */
  public async verifyActualConnectivity(): Promise<boolean> {
    if (typeof window === 'undefined') return true;
    if (!navigator.onLine) {
      this.updateState({ isOnline: false });
      return false;
    }

    try {
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 3000);
      const res = await fetch('/api/v1/auth/me', {
        method: 'HEAD',
        signal: controller.signal
      }).catch(() => null);
      clearTimeout(timeoutId);

      const isConnected = res !== null;
      this.updateState({ isOnline: isConnected });
      return isConnected;
    } catch {
      this.updateState({ isOnline: false });
      return false;
    }
  }

  /**
   * Trigger 1-click native install prompt
   */
  public async promptInstall(): Promise<'accepted' | 'dismissed' | 'unavailable'> {
    if (!this.deferredInstallPrompt) {
      // In iOS Safari, guide the user to Add to Home Screen
      if (this.isIos()) {
        alert("To install DOC SEARCH on iOS:\n1. Tap the Share button in Safari (box with arrow)\n2. Scroll down and tap 'Add to Home Screen' (+)\n3. Tap 'Add' to launch in full-screen app mode.");
        return 'dismissed';
      }
      return 'unavailable';
    }

    try {
      this.deferredInstallPrompt.prompt();
      const choiceResult = await this.deferredInstallPrompt.userChoice;
      if (choiceResult.outcome === 'accepted') {
        console.log('[PWA] User accepted installation prompt');
        this.deferredInstallPrompt = null;
        this.updateState({ isInstallable: false, isInstalled: true });
        return 'accepted';
      } else {
        console.log('[PWA] User dismissed installation prompt');
        return 'dismissed';
      }
    } catch (e) {
      console.error('[PWA] Install prompt error:', e);
      return 'unavailable';
    }
  }

  public isIos(): boolean {
    if (typeof window === 'undefined') return false;
    const ua = window.navigator.userAgent.toLowerCase();
    return /iphone|ipad|ipod/.test(ua);
  }

  /**
   * Trigger service worker update & app refresh
   */
  public updateApp(): void {
    if (this.registration && this.registration.waiting) {
      this.registration.waiting.postMessage({ type: 'SKIP_WAITING' });
    }
    window.location.reload();
  }

  public getState(): PwaState {
    return { ...this.state };
  }

  public destroy(): void {
    if (this.pingInterval) {
      clearInterval(this.pingInterval);
      this.pingInterval = null;
    }
  }

  public subscribe(listener: PwaListener): () => void {
    this.listeners.add(listener);
    listener(this.getState());
    return () => {
      this.listeners.delete(listener);
    };
  }

  private updateState(partial: Partial<PwaState>): void {
    this.state = { ...this.state, ...partial };
    for (const listener of this.listeners) {
      try {
        listener(this.getState());
      } catch (err) {
        console.error('[PWA] Listener notice:', err);
      }
    }
  }
}

export const pwaCompanion = new PwaCompanion();
