import React from 'react';
import type { InfrastructureAlertDto } from '@docsearch/api-contracts';
import {
  Card,
  Badge,
  TableContainer,
  Table,
  TableHeader,
  TableBody,
  TableRow,
  TableHead,
  TableCell
} from '@docsearch/ui-kit';

export interface InfrastructureAlertCenterViewProps {
  alerts: InfrastructureAlertDto[];
}

export const InfrastructureAlertCenterView: React.FC<InfrastructureAlertCenterViewProps> = ({ alerts }) => {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
      <Card
        title="Infrastructure Alert Feed & Anomaly Warnings"
        subtitle="Automated alerts generated by cluster thresholds, connection pool bursts, and latency spikes"
        padding="none"
      >
        <TableContainer style={{ border: 'none', borderRadius: '0' }}>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Alert Code</TableHead>
                <TableHead>Title & Description</TableHead>
                <TableHead>Severity</TableHead>
                <TableHead>Type</TableHead>
                <TableHead>Resource Reference</TableHead>
                <TableHead>Detected At</TableHead>
                <TableHead>Status</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {alerts.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={7} style={{ textAlign: 'center', color: 'var(--ds-color-text-muted)', padding: '24px' }}>
                    Zero active infrastructure alerts.
                  </TableCell>
                </TableRow>
              ) : (
                alerts.map((a) => (
                  <TableRow key={a.id}>
                    <TableCell style={{ fontFamily: 'var(--ds-font-mono)', fontWeight: '700', fontSize: '0.75rem' }}>
                      {a.alertCode}
                    </TableCell>
                    <TableCell style={{ maxWidth: '300px' }}>
                      <strong style={{ fontSize: '0.8125rem', color: 'var(--ds-color-text-primary)', display: 'block', marginBottom: '2px' }}>
                        {a.title}
                      </strong>
                      <p style={{ margin: 0, fontSize: '0.75rem', color: 'var(--ds-color-text-secondary)' }}>
                        {a.description}
                      </p>
                    </TableCell>
                    <TableCell>
                      <Badge
                        variant={
                          a.severity === 'CRITICAL'
                            ? 'danger'
                            : a.severity === 'HIGH' || a.severity === 'MEDIUM'
                            ? 'warning'
                            : 'neutral'
                        }
                      >
                        {a.severity}
                      </Badge>
                    </TableCell>
                    <TableCell style={{ fontSize: '0.75rem', fontFamily: 'var(--ds-font-mono)' }}>
                      {a.alertType}
                    </TableCell>
                    <TableCell style={{ fontSize: '0.75rem', fontFamily: 'var(--ds-font-mono)' }}>
                      {a.resourceReference}
                    </TableCell>
                    <TableCell style={{ fontSize: '0.75rem', color: 'var(--ds-color-text-muted)', whiteSpace: 'nowrap' }}>
                      {new Date(a.detectedAt).toLocaleString()}
                    </TableCell>
                    <TableCell>
                      <Badge variant={a.status === 'RESOLVED' ? 'success' : a.status === 'OPEN' ? 'danger' : 'warning'}>
                        {a.status}
                      </Badge>
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </TableContainer>
      </Card>
    </div>
  );
};
