export const themes = {
  ADVANCE_PRO: 'theme-advance-pro',
  OBSIDIAN_TITANIUM: 'theme-obsidian-titanium',
  IMPERIAL_GOLD: 'theme-imperial-gold',
  QUANTUM_BIOLUM: 'theme-quantum-biolum',
  TOKYO_CYBERPUNK: 'theme-tokyo-cyberpunk',
  SOLAR_AMBER: 'theme-solar-amber',
  SWISS_CLINICAL: 'theme-swiss-clinical',
  DAYLIGHT_CLINIC: 'theme-daylight-clinic',
  AURORA_GLOW: 'theme-aurora-glow',

  NORDIC_PURE: 'theme-nordic-pure',
  OCEANIC_NAVY: 'theme-oceanic-navy',
  AYUR_WELLNESS: 'theme-ayur-wellness',
  CYBER_SURGEON: 'theme-cyber-surgeon',
  ROSE_CARE: 'theme-rose-care',
  HEALTHCARE_LIGHT: 'theme-healthcare-light',
  BLACK_WHITE: 'theme-black-white'
} as const;

export type ThemeMode = (typeof themes)[keyof typeof themes];

export const colorVariables = {
  background: 'var(--ds-color-bg)',
  surface: 'var(--ds-color-surface)',
  surfaceSubtle: 'var(--ds-color-surface-subtle)',
  surfaceHover: 'var(--ds-color-surface-hover)',
  surfaceSelected: 'var(--ds-color-surface-selected, rgba(2, 132, 199, 0.16))',
  elevatedSurface: 'var(--ds-surface-l4, var(--ds-color-surface))',
  border: 'var(--ds-color-border)',
  borderSubtle: 'var(--ds-color-border-subtle)',
  borderStrong: 'var(--ds-color-border-strong)',
  divider: 'var(--ds-color-border-subtle, var(--ds-color-border))',
  textPrimary: 'var(--ds-color-text-primary)',
  textSecondary: 'var(--ds-color-text-secondary)',
  textMuted: 'var(--ds-color-text-muted)',
  textInverse: 'var(--ds-color-text-inverse, #ffffff)',
  primary: 'var(--ds-color-primary)',
  primaryHover: 'var(--ds-color-primary-hover)',
  primarySubtle: 'var(--ds-color-primary-subtle)',
  primaryForeground: 'var(--ds-color-primary-foreground)',
  secondary: 'var(--ds-color-secondary)',
  secondaryHover: 'var(--ds-color-secondary-hover)',
  secondarySubtle: 'var(--ds-color-secondary-subtle)',
  secondaryForeground: 'var(--ds-color-secondary-foreground)',
  accent: 'var(--ds-color-accent)',
  accentHover: 'var(--ds-color-accent-hover)',
  accentForeground: 'var(--ds-color-accent-foreground)',
  danger: 'var(--ds-color-danger)',
  dangerHover: 'var(--ds-color-danger-hover, #dc2626)',
  dangerSubtle: 'var(--ds-color-danger-subtle)',
  dangerForeground: 'var(--ds-color-danger-foreground)',
  warning: 'var(--ds-color-warning)',
  warningHover: 'var(--ds-color-warning-hover, #d97706)',
  warningSubtle: 'var(--ds-color-warning-subtle)',
  warningForeground: 'var(--ds-color-warning-foreground)',
  success: 'var(--ds-color-success)',
  successHover: 'var(--ds-color-success-hover, #059669)',
  successSubtle: 'var(--ds-color-success-subtle)',
  successForeground: 'var(--ds-color-success-foreground)',
  focus: 'var(--ds-color-focus-ring)',
  focusRing: 'var(--ds-color-focus-ring)',
  overlay: 'var(--ds-color-backdrop)',
  backdrop: 'var(--ds-color-backdrop)',
  // Universal Semantic Status Tokens
  statusActive: 'var(--ds-status-active, var(--ds-color-primary))',
  statusInactive: 'var(--ds-status-inactive, var(--ds-color-text-muted))',
  statusPending: 'var(--ds-status-pending, var(--ds-color-warning))',
  statusApproved: 'var(--ds-status-approved, var(--ds-color-success))',
  statusRejected: 'var(--ds-status-rejected, var(--ds-color-danger))',
  statusDraft: 'var(--ds-status-draft, var(--ds-color-text-secondary))',
  statusProcessing: 'var(--ds-status-processing, var(--ds-color-accent))',
  statusCompleted: 'var(--ds-status-completed, var(--ds-color-success))',
  statusFailed: 'var(--ds-status-failed, var(--ds-color-danger))',
  statusExpired: 'var(--ds-status-expired, var(--ds-color-text-muted))',
  statusWarning: 'var(--ds-status-warning, var(--ds-color-warning))',
  statusCritical: 'var(--ds-status-critical, #ef4444)',
  statusInfo: 'var(--ds-status-info, var(--ds-color-accent))'
} as const;
