/**
 * Phase 1: Company Platform (Doc Search Internal Governance & SaaS Ops)
 *
 * Scope: 15 Frozen Domains:
 * 1. Executive & Command Center (Implemented v1.0)
 * 2. CRM & Partner Lifecycle (Implemented v1.0)
 * 3. Product / Plans / Entitlements (Implemented v1.0)
 * 4. Subscription / Billing / Finance (Implemented v1.0)
 * 5. Sales & Marketing (Implemented v1.0)
 * 6. Customer Success & Support (Implemented v1.0)
 * 7. Communication & Content (Implemented v1.0)
 * 8. Analytics / BI / Intelligence (Implemented v1.0)
 * 9. AI Platform & AI Governance (Implemented v1.0)
 * 10. Security / RBAC / Policy / Audit (Implemented v1.0)
 * 11. Compliance & Data Governance (Implemented v1.0)
 * 12. API / Integration / Interoperability (Implemented v1.0)
 * 13. Platform Engineering (Implemented v1.0)
 * 14. Infrastructure / Monitoring / DR
 * 15. Company Administration & Governance
 */

export * from './types/executive.js';
export * from './services/executive-service.js';
export * from './services/mock-data.js';
export * from './services/partner-service.js';
export * from './services/mock-partner-data.js';
export * from './services/product-service.js';
export * from './services/mock-product-data.js';
export * from './services/subscription-service.js';
export * from './services/mock-subscription-data.js';
export * from './services/sales-marketing-service.js';
export * from './services/mock-sales-marketing-data.js';
export * from './services/support-service.js';
export * from './services/mock-support-data.js';
export * from './services/communication-service.js';
export * from './services/mock-communication-data.js';
export * from './services/analytics-service.js';
export * from './services/mock-analytics-data.js';
export * from './services/ai-service.js';
export * from './services/mock-ai-data.js';
export * from './services/security-service.js';
export * from './services/mock-security-data.js';
export * from './services/compliance-service.js';
export * from './services/mock-compliance-data.js';
export * from './services/integration-service.js';
export * from './services/mock-integration-data.js';
export * from './services/platform-engineering-service.js';
export * from './services/mock-platform-engineering-data.js';
export * from './navigation/phase1-nav.js';
export * from './components/CompanyShell.js';
export * from './components/executive/ExecutiveCommandCenter.js';
export * from './components/executive/ExecutiveOverview.js';
export * from './components/executive/KpiSummary.js';
export * from './components/executive/BusinessPerformance.js';
export * from './components/executive/AlertsSection.js';
export * from './components/executive/RecentActivities.js';
export * from './components/executive/QuickActions.js';
export * from './components/executive/TrendAnalytics.js';
export * from './components/executive/SystemHealthSummary.js';
export * from './components/crm/PartnerLifecycleManager.js';
export * from './components/crm/PartnerListView.js';
export * from './components/crm/PartnerProfileView.js';
export * from './components/crm/PartnerActivityTimeline.js';
export * from './components/crm/PartnerLifecycleTransitionDialog.js';
export * from './components/product/ProductDomainManager.js';
export * from './components/product/ProductListView.js';
export * from './components/product/ProductProfileView.js';
export * from './components/product/PlanListView.js';
export * from './components/product/PlanProfileView.js';
export * from './components/product/FeatureCatalogView.js';
export * from './components/product/PartnerAssignmentView.js';
export * from './components/product/AssignPlanDialog.js';
export * from './components/billing/FinanceDomainManager.js';
export * from './components/billing/FinanceOverviewView.js';
export * from './components/billing/SubscriptionListView.js';
export * from './components/billing/SubscriptionProfileView.js';
export * from './components/billing/SubscriptionTransitionDialog.js';
export * from './components/billing/BillingAccountListView.js';
export * from './components/billing/InvoiceListView.js';
export * from './components/billing/InvoiceProfileView.js';
export * from './components/billing/PaymentRecordListView.js';
export * from './components/sales/SalesMarketingDomainManager.js';
export * from './components/sales/SalesOverviewView.js';
export * from './components/sales/LeadListView.js';
export * from './components/sales/LeadProfileView.js';
export * from './components/sales/OpportunityListView.js';
export * from './components/sales/OpportunityProfileView.js';
export * from './components/sales/OpportunityTransitionDialog.js';
export * from './components/sales/PartnerSalesView.js';
export * from './components/sales/CampaignListView.js';
export * from './components/sales/CampaignProfileView.js';
export * from './components/sales/MarketingActivityListView.js';
export * from './components/sales/SalesTaskListView.js';
export * from './components/support/CustomerSuccessDomainManager.js';
export * from './components/support/SuccessOverviewView.js';
export * from './components/support/TicketListView.js';
export * from './components/support/TicketProfileView.js';
export * from './components/support/TicketTransitionDialog.js';
export * from './components/support/PartnerHealthListView.js';
export * from './components/support/SlaMonitoringView.js';
export * from './components/support/SuccessCheckinListView.js';
export * from './components/communication/CommunicationDomainManager.js';
export * from './components/communication/CommunicationOverviewView.js';
export * from './components/communication/AnnouncementListView.js';
export * from './components/communication/AnnouncementProfileView.js';
export * from './components/communication/ReleaseBroadcastView.js';
export * from './components/communication/OperationalBulletinView.js';
export * from './components/communication/NotificationTemplateListView.js';
export * from './components/communication/DispatchRecordListView.js';
export * from './components/communication/ContentTransitionDialog.js';
export * from './components/analytics/AnalyticsDomainManager.js';
export * from './components/analytics/AnalyticsOverviewView.js';
export * from './components/analytics/PlatformUsageView.js';
export * from './components/analytics/ApiTelemetryView.js';
export * from './components/analytics/TenantSegmentationView.js';
export * from './components/analytics/SystemInsightCenterView.js';
export * from './components/analytics/SavedReportListView.js';
export * from './components/ai/AIDomainManager.js';
export * from './components/ai/AIOverviewView.js';
export * from './components/ai/AIModelRegistryView.js';
export * from './components/ai/AIModelProfileView.js';
export * from './components/ai/AIGovernanceView.js';
export * from './components/ai/PromptRegistryView.js';
export * from './components/ai/PromptVersionProfileView.js';
export * from './components/ai/AIUsageQuotaView.js';
export * from './components/ai/AIAuditTraceView.js';
export * from './components/ai/AISafetyCenterView.js';
export * from './components/ai/PolicyTransitionDialog.js';
export * from './components/ai/PromptApprovalDialog.js';
export * from './components/security/SecurityDomainManager.js';
export * from './components/security/SecurityOverviewView.js';
export * from './components/security/RoleListView.js';
export * from './components/security/RoleProfileView.js';
export * from './components/security/PermissionMatrixView.js';
export * from './components/security/UserAccessView.js';
export * from './components/security/SecurityPolicyListView.js';
export * from './components/security/SecurityPolicyProfileView.js';
export * from './components/security/AuditEventExplorerView.js';
export * from './components/security/AuditVerificationView.js';
export * from './components/security/SessionInspectionView.js';
export * from './components/security/CredentialLifecycleView.js';
export * from './components/security/SecurityIncidentCenterView.js';
export { SecurityPolicyTransitionDialog } from './components/security/PolicyTransitionDialog.js';
export * from './components/security/SessionTerminationDialog.js';
export * from './components/security/CredentialActionDialog.js';
export * from './components/compliance/ComplianceDomainManager.js';
export * from './components/compliance/ComplianceOverviewView.js';
export * from './components/compliance/ComplianceFrameworkListView.js';
export * from './components/compliance/ComplianceFrameworkProfileView.js';
export * from './components/compliance/ComplianceControlListView.js';
export * from './components/compliance/ComplianceEvidenceListView.js';
export * from './components/compliance/ComplianceEvidenceProfileView.js';
export * from './components/compliance/ComplianceControlMappingView.js';
export * from './components/compliance/DataGovernanceView.js';
export * from './components/compliance/RetentionPolicyListView.js';
export * from './components/compliance/RetentionPolicyProfileView.js';
export * from './components/compliance/BAAComplianceView.js';
export * from './components/compliance/GovernanceExceptionView.js';
export * from './components/compliance/ComplianceVerificationView.js';
export * from './components/compliance/VerifyControlDialog.js';
export * from './components/compliance/ExceptionReviewDialog.js';
export * from './components/integration/IntegrationDomainManager.js';
export * from './components/integration/IntegrationOverviewView.js';
export * from './components/integration/ApiRouteRegistryView.js';
export * from './components/integration/ApiRouteProfileView.js';
export * from './components/integration/ApiVersionManagementView.js';
export * from './components/integration/IntegrationProviderListView.js';
export * from './components/integration/IntegrationProviderProfileView.js';
export * from './components/integration/IntegrationConnectionView.js';
export * from './components/integration/HL7InteroperabilityView.js';
export * from './components/integration/FHIRInteroperabilityView.js';
export * from './components/integration/WebhookCenterView.js';
export * from './components/integration/ApiRateLimitView.js';
export * from './components/integration/IntegrationHealthView.js';
export * from './components/integration/IntegrationIncidentCenterView.js';
export * from './components/integration/IntegrationCredentialLifecycleView.js';
export * from './components/integration/IntegrationAuditTraceView.js';
export * from './components/integration/ConnectionTestDialog.js';
export * from './components/integration/WebhookRetryDialog.js';
export * from './components/integration/IncidentActionDialog.js';
export * from './components/integration/CredentialRotateDialog.js';
export * from './components/integration/ApiDeprecateDialog.js';
export * from './components/platform-engineering/PlatformEngineeringDomainManager.js';
export * from './components/platform-engineering/PlatformEngineeringOverviewView.js';
export * from './components/platform-engineering/BuildPipelineListView.js';
export * from './components/platform-engineering/BuildPipelineProfileView.js';
export * from './components/platform-engineering/BuildRunExplorerView.js';
export * from './components/platform-engineering/CICDPipelineListView.js';
export * from './components/platform-engineering/CICDRunExplorerView.js';
export * from './components/platform-engineering/ArtifactRepositoryListView.js';
export * from './components/platform-engineering/ArtifactExplorerView.js';
export * from './components/platform-engineering/EnvironmentListView.js';
export * from './components/platform-engineering/EnvironmentConfigurationView.js';
export * from './components/platform-engineering/DependencyGraphView.js';
export * from './components/platform-engineering/DependencyNodeProfileView.js';
export * from './components/platform-engineering/PackageReleaseListView.js';
export * from './components/platform-engineering/DeploymentListView.js';
export * from './components/platform-engineering/DeveloperExperienceView.js';
export * from './components/platform-engineering/PlatformIncidentCenterView.js';
export * from './components/platform-engineering/PlatformAuditTraceView.js';
export * from './components/platform-engineering/RunBuildDialog.js';
export * from './components/platform-engineering/DeploymentPromotionDialog.js';
export * from './components/platform-engineering/DeploymentRollbackDialog.js';
export * from './components/platform-engineering/ReleasePromoteDialog.js';
export * from './components/platform-engineering/PlatformIncidentActionDialog.js';
export * from './services/infrastructure-service.js';
export * from './services/mock-infrastructure-data.js';
export * from './components/infrastructure/InfrastructureDomainManager.js';
export * from './components/infrastructure/InfrastructureOverviewView.js';
export * from './components/infrastructure/InfrastructureTopologyView.js';
export * from './components/infrastructure/InfrastructureComputeView.js';
export * from './components/infrastructure/InfrastructureServiceView.js';
export * from './components/infrastructure/InfrastructureDatabaseView.js';
export * from './components/infrastructure/DatabaseConnectionPoolView.js';
export * from './components/infrastructure/InfrastructureHealthView.js';
export * from './components/infrastructure/InfrastructureAlertCenterView.js';
export * from './components/infrastructure/InfrastructureIncidentCenterView.js';
export * from './components/infrastructure/BackupPolicyView.js';
export * from './components/infrastructure/BackupRecordView.js';
export * from './components/infrastructure/RestoreVerificationView.js';
export * from './components/infrastructure/InfrastructureRegionView.js';
export * from './components/infrastructure/InfrastructureReplicationView.js';
export * from './components/infrastructure/DisasterRecoveryPlanView.js';
export * from './components/infrastructure/DisasterRecoveryDrillView.js';
export * from './components/infrastructure/InfrastructureAuditTraceView.js';
export * from './components/infrastructure/InfrastructureIncidentActionDialog.js';
export * from './components/infrastructure/FailoverActionDialog.js';
export * from './components/infrastructure/BackupTriggerDialog.js';
export * from './components/infrastructure/DrillExecuteDialog.js';
export * from './services/company-admin-service.js';
export * from './services/mock-company-admin-data.js';
export * from './components/company-admin/CompanyAdminDomainManager.js';
export * from './components/company-admin/CompanyOverviewView.js';
export * from './components/company-admin/LegalEntityListView.js';
export * from './components/company-admin/DepartmentHierarchyView.js';
export * from './components/company-admin/EmployeeDirectoryView.js';
export * from './components/company-admin/DesignationListView.js';
export * from './components/company-admin/BoardGovernanceView.js';
export * from './components/company-admin/CorporatePolicyView.js';
export * from './components/company-admin/ComplianceOfficerCenterView.js';
export * from './components/company-admin/GovernanceCalendarView.js';
export * from './components/company-admin/CompanyAuditTraceView.js';
export * from './components/company-admin/EmployeeStatusDialog.js';
export * from './components/company-admin/PolicyApprovalDialog.js';
export * from './components/company-admin/GovernanceEventActionDialog.js';
export * from './components/company-admin/OfficerAppointDialog.js';


